myapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'myapp'

urlpatterns = [
    # xunbao/
    url(r'^$', views.index, name='index'),

    # xunbao/login/
    url(r'^login/$', views.my_login, name='login'),

    # xunbao/leaderboard/
    url(r'^leaderboard/$', views.leaderboard, name='leaderboard'),

    # logout
    url(r'^logout/$', views.my_logout, name='logout'),

    # /xunbao/developers/
    url(r'^developers/$', views.developers, name='developers'),
    
    #api's
    url(r'^getq/$', views.User_list),
    url(r'^checkans/$', views.checkans),
    url(r'^leaderboard_api/$', views.lead_api),
    url(r'^status/$', views.status),
    url(r'^logs/$', views.logs_data),
]

xunbao/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('myapp.urls')),

    # social login with google and github
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from datetime import datetime
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    solved = models.IntegerField(default=1)
    timetaken = models.DateTimeField(default=datetime.now)

    class Meta:
        ordering = ['-solved', 'timetaken']

    def __str__(self):
        return self.user.first_name + self.user.last_name


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Problems(models.Model):
    desc = models.CharField(max_length=100000, blank=True)
    image = models.FileField(blank=True)
    ans = models.CharField(max_length=10000, null=True)
    mydate = models.DateTimeField(default=datetime.now)
    val = models.IntegerField(blank=False,default=1)
    #pk = models.AutoField(primary_key=True)
    def __str__(self):
        return self.desc


class logs(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    answer = models.CharField(max_length=10000)
    time = models.DateTimeField(default=datetime.now)
    status = models.BooleanField(default = False)
    def __str__(self):
        return self.user.username

myapp/forms.py
from django import forms


class AnswerForm(forms.Form):
    ans = forms.CharField(label='Answer here...', max_length=1000)

myapp/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from datetime import datetime
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .models import Problems, Profile, logs
from .forms import AnswerForm
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from django.http import HttpResponse, JsonResponse
from .serializers import UserSerializer,LeaderboardSerializers,ProblemsSerializer
from django.contrib.auth.models import User
from rest_framework.views import APIView
from django.utils.six import BytesIO
import json
from social_django.models import UserSocialAuth

app_name = 'myapp'


@login_required
def index(request):
    user = request.user
    if not request.user.is_superuser :
        if not user.username.isnumeric():
            fid = user.social_auth.get(provider='facebook').uid
            x = Profile.objects.filter(user__username = fid)
            if not x:
                user.username = fid
            else:
                x=x[0]
                z = x.solved
                y = x.timetaken
                x.user.delete()
                user.username = fid
                user.solved = z
                user.timetaken = y
    user.save()

    problems = Problems.objects.order_by('mydate')
    myprofile = Profile.objects.get(user=user)
    count = myprofile.solved
    total = Problems.objects.all().count
    myproblem = problems[0]
    i = 1
    for problem in problems:
        if i == count:
            myproblem = problem
            break
        i = i + 1
    msg = 'Wishing you good luck!'
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            log = logs.objects.create(answer = form.cleaned_data['ans'].lower(),user = request.user)
            log.save()
            if form.cleaned_data['ans'].lower() == myproblem.ans.lower():
                log.status = True
                log.save()
                myprofile.solved = count + 1
                myprofile.timetaken = datetime.now()
                myprofile.save()
                return HttpResponseRedirect(reverse('myapp:index'))
            else:
                msg = 'Incorrect answer, please try again!'
    else:
        form = AnswerForm()
    return render(request, 'myapp/index.html', {
        'problems': problems,
        'count': count,
        'form': form,
        'msg': msg,
        'total': total,
    })


def my_login(request):
    return render(request, 'myapp/register.html', {})


def leaderboard(request):
    profiles = Profile.objects.all()
    return render(request, 'myapp/leaderboard.html', {
        'profiles': profiles,
    })


def my_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))


def developers(request):
    return render(request, 'myapp/developers.html', {})



@csrf_exempt
def User_list(request):
    if request.method == 'POST':
        user = request.POST
        if(user['skey'] != 'sexokashish'):
            strin = [{'response':"0"},]
            return JsonResponse(strin,safe=False)
        fname = user['fname']
        lname = user['lname']
        uid = user['fid']
        user , created = User.objects.get_or_create(username = uid,first_name=fname,last_name=lname)
        myprofile, created = Profile.objects.get_or_create(user=user)
        counter = myprofile.solved
        total = Problems.objects.all().count()
        if total < counter:
            strin = [{'response':"you win"},]
            return JsonResponse(strin,safe=False)
        Problem = Problems.objects.filter(val = counter)
        serializer = ProblemsSerializer(Problem, many=True)
        return JsonResponse(serializer.data, safe=False)



@csrf_exempt
def lead_api(request):
    if(request.method == 'GET'):
        users = Profile.objects.all().exclude(user__is_superuser = True)
        serializer = LeaderboardSerializers(users,many = True)
        return JsonResponse(serializer.data,safe=False)
    else:
        pass


@csrf_exempt
def checkans(request):
    if request.method == 'POST':
        user = request.POST
        ans = user['ans'].lower()
        if(user['skey'] != 'sexokashish'):
            strin = {'response':"0"}
            return JsonResponse(strin,safe=False)
        user = user['email']
        print(ans)
        user = User.objects.get(username = user)
        log = logs.objects.create(answer = ans,user = user)
        log.save()
        problems = Problems.objects.all().order_by('mydate')          
        myprofile = Profile.objects.get(user=user)
        count = myprofile.solved
        total = Problems.objects.all().count()
        if total < count:
                strin = {'response':"you win"}
                return JsonResponse(strin,safe=False)
        myproblem = problems[0]
        i = 1
        for problem in problems:
            if i == count:
                myproblem = problem
                break
            i = i + 1
        if ans == myproblem.ans.lower():
            log.status = True
            log.save()
            myprofile.solved = count + 1
            myprofile.timetaken = datetime.now()
            myprofile.save()
            strin = {'response':"1"}
            return JsonResponse(strin,safe=False)
        else:      
            strin = {'response':"0"}
            return JsonResponse(strin,safe=False)
    return JsonResponse(user.errors, status=400)

@login_required
def logs_data(request):
    log = logs.objects.all().order_by('-time')
    if request.user.is_superuser:
        return render(request,'myapp/logs_data.html',{'logs':log})
    else:
        return HttpResponse('You are not authenticated.')



def status(request):
    if request.method == "GET":
        #return JsonResponse(1,safe = False) #coming soon
        #return JsonResponse(2,safe = False) #started
        return JsonResponse(3,safe = False) #end

myapp/templates/myapp/answer_form.html
<form action="" enctype="multipart/form-data" method="post" role="form">
    {% csrf_token %}
    {% include 'Classes/form-template.html' %}
    <button type="submit">Submit</button>
</form>

myapp/templates/myapp/base.html
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Xunbao{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Satisfy" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"></script>
    <script src="{% static 'js/myjs.js' %}"></script>
    <style type="text/css">
        {%block style%}
        {%endblock%}
    </style>
</head>
<!-- <body style="background: url('https://www.indeedcare.com/site/wp-content/uploads/2014/02/002-blurred-background-texture-vol2.png'); background-repeat: no-repeat; background-attachment: fixed; background-size: cover;" > -->
<!-- <body style="background: url('https://raw.githubusercontent.com/Manan-YMCA/EC2018App/master/app/src/main/res/drawable/back_xunbao.jpg'); background-repeat: no-repeat; background-attachment: fixed; background-size: cover;" > -->
<body style="background-image: url({% static 'images/back_xunbao.jpg' %}); background-repeat: no-repeat; background-attachment: fixed; background-size: cover;" >
        <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1170777389726576',
      xfbml      : true,
      version    : 'v2.12'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
    <nav class="navbar navbar-default" style="background-color: #f2e7cb87; padding: 3px; border: 0;">
        <!-- <div class="container-fluid"> -->
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'myapp:index' %}" style="font-size: 30px;"><img class="img-responsive2"
           src="{% static 'images/xunbao_logo.png' %}" style="width:120px;height:auto;margin-top:-10px"></a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">   <!-- anything in this div is going to be hidden-->
                <ul class="nav navbar-nav">
                    <li class="">
                        <a style="color: #43362c;" href="{% url 'myapp:index' %}">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                        </a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                    {% if request.user.is_authenticated %}
                        <a style="color: #43362c;" href="">
                            <strong>Hey {{ user.first_name }}! </strong>
                        </a>
                    {% endif %}
                    </li>
                    <li class="">
                        <a style="color: #43362c;" href="{% url 'myapp:leaderboard' %}">
                            <span class="glyphicon glyphicon-list" aria-hidden="true"></span>&nbsp; Leaderboard
                        </a>
                    </li>
                    <li class="">
                        <a style="color: #43362c;" href="{% url 'myapp:developers' %}">
                            <span class="glyphicon glyphicon-certificate" aria-hidden="true"></span>&nbsp; Developers
                        </a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="">
                        {% block loga %}<a href="{% url 'myapp:logout' %}">{% endblock %}
                            {% block log %}<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout{% endblock %}
                        </a>
                    </li>
{% endif %}
                </ul>
            </div>
        <!-- </div> -->
    </nav>
    {% block body %}
    {% endblock %}

</body>
</html>

myapp/templates/myapp/developers.html
{% extends 'myapp/base.html' %}
{%load static%}
{% block body %}
  <style scoped>
.flip-container{
  width:100%;
  height:400px;
  position: relative;
}
.card{
  text-align:center;
  position: absolute;
  width: 100%;
  height: 100%;

margin-top: 100px;
  border-radius: 1em;
}
.face {
  position: absolute;
  width: 100%;
  height: 100%;
}
.face.front{
  background:#000;
}
.face.back {
  display: block;
  box-sizing: border-box;
  padding: 20px;
  color: white;
  text-align: left;
  background-color: #333;
}
.container{
  perspective: 800px;
}
.card{
  transform-style: preserve-3d;
  transition: all 1.0s linear;
  border-radius: 1em;
  margin-top: 10px;
}
.card:hover .front{
  transform: rotateY(-180deg);
}
.card:hover .back {
 transform: rotateY(0deg);
}
.face {
  backface-visibility: hidden;
  transform-style: preserve-3d;
  transition: 0.5s;
}
.face.front {
  transform: rotateY(0deg);
border-radius: 1em;
}
.face.back {
  transform: rotateY(180deg);
}
.face.front h3, h4{
  color:#fff;
  margin-top: 20px;
}
.face.front a{
  color: #f13f89;
  text-decoration: none;
}
.face.back p {
    font-size: 18px;
    margin-top: 35px;
}
.carder{
  margin-top: 40px;
}
</style>
<body>
  <div class="container-fluid">
    <div class="row no-gutters" style="margin-bottom: 20px;">

    <div class="col-md-4" align="center" style="margin-top: 20px;">
      <div class="flip-container">
   <div class="card">
      <div class="face front">
        <img style="height: 75%;width: 100%;  border-radius: 1em; " src="https://scontent.fdel3-1.fna.fbcdn.net/v/t1.0-9/20768116_1483758871714836_8735224781601887776_n.jpg?oh=faf47b3cbc998e6e98d51aa1c3b61018&oe=5AEAC44B">
        <h3>Ajay Verma</h3>
        <h4 style="color:#fff">Backend Developer</h4>
      </div>
      <div class="face back">
        <p>He is Ajay Verma, 6th semester student pursuing IT in YMCA University , Faridabad. He is a sports programmer who love to solve programming problems and develop web applications. He loves coding, philosophy and sleeping of-course !<br><br/><center>
    <a href="https://www.facebook.com/avcool1">
  <img border="0" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/F_icon.svg/1000px-F_icon.svg.png" width="60" height="60">
  </a>
  <a href="https://github.com/scorpion-ajay">
  <img border="0" src="http://alexi-garrow.com/octocat_outline.png" width="60" height="60">
  </a>
  <a href="http://manantechnosurge.com/member/7009454212/">
  <img border="0" src="https://scontent.fdel3-1.fna.fbcdn.net/v/t1.0-1/c50.0.200.200/p200x200/12742693_1111335255567791_2797602291257818265_n.png?oh=73358cc20d08c82f6bb2063b0db7e2ae&oe=5B2610C4" width="60" height="60">
  </a></center></p>
      </div>
    </div>
   </div>
  </div>
    <div class="col-md-4" align="center" style="margin-top: 20px;">
      <div class="flip-container">
   <div class="card">
      <div class="face front">
        <img style="height: 75%;width: 100%;  border-radius: 1em;" src="{% static 'images/sahil1.jpg' %}">
        <h3>Sahil Singla</h3>
        <h4 style="color:#fff">Database and API Developer</h4>
      </div>
      <div class="face back">
        <p>He is a CE 4th sem student in YMCAUST, Faridabad. He is a Django Developer, Fitness Lover, Adventurous Person, a Curious and Enthusiastic Programmer who loves problem solving.<br><br><br><center>
   <a href="https://www.facebook.com/sahil.singla.3388">
  <img border="0" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/F_icon.svg/1000px-F_icon.svg.png" width="60" height="60">
  </a>
  <a href="https://github.com/singlasahil221">
  <img border="0" src="http://alexi-garrow.com/octocat_outline.png" width="60" height="60">
  </a>
  <a href="http://manantechnosurge.com/member/8745959048/">
  <img border="0" src="https://scontent.fdel3-1.fna.fbcdn.net/v/t1.0-1/c50.0.200.200/p200x200/12742693_1111335255567791_2797602291257818265_n.png?oh=73358cc20d08c82f6bb2063b0db7e2ae&oe=5B2610C4" width="60" height="60"></a></center></p>
      </div>
    </div>
    </div>

  </div>
  <div class="col-md-4" align="center" style="margin-top: 20px;">
    <div class="flip-container" >
     <div class="card" >
        <div class="face front" style="border-radius: 1em;">
          <img class="responsive" style="width: 100%; height: 75%; border-radius: 1em;" src="{% static 'images/mohit.jpg' %}" alt="bg">
          <h3>Mohit Yadav</h3>
          <h4 style="color:#fff">Frontend Developer</h4>

        </div>
        <div class="face back">
          <p>He is a IT 4th sem student in YMCAUST, Faridabad. He loves to code and make ideas come to life.<br><br/><center>
    <a href="https://www.linkedin.com/in/mohityadav7/">
    <img border="0" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/F_icon.svg/1000px-F_icon.svg.png" width="60" height="60">
    </a>
    <a href="https://github.com/princebatra2315">
    <img border="0" src="http://alexi-garrow.com/octocat_outline.png" width="60" height="60">
    </a>
    <a href="http://manantechnosurge.com/member/9953764100/">
    <img border="0" src="https://scontent.fdel3-1.fna.fbcdn.net/v/t1.0-1/c50.0.200.200/p200x200/12742693_1111335255567791_2797602291257818265_n.png?oh=73358cc20d08c82f6bb2063b0db7e2ae&oe=5B2610C4" width="60" height="60">
    </a></center></p>
        </div>
      </div>
      </div>

    </div>
  </div>
  </div>


</body>
{% endblock %}

myapp/templates/myapp/form-template.html
{% for field in form %}
    <label>{{ field.label_tag }}</label>
    {{ field }}
    <br>
{% endfor %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{%load static%}
{% block body %}
<div class="">

</div>
<div class="container">
    <div class="panel panel-transparent">
        <div class="panel-body p-3">
            {% for problem in problems %}
                {% if forloop.counter == count %}
                    <h2 style="text-align:center;">Level : {{ forloop.counter }}</h2>
                    <h4 style="text-align:center;">{{ problem.desc }}</h4>
                    {% if problem.image %}
                    <img src="/media/{{ problem.image }}" class="center img-responsive" style="width: 300px; height: 200px;">
                    {% endif %}
                    {{ break }}
                {% endif %}
            {% endfor %}
            {% if count > total %}
                <h3>Congrats, you have solved all of the problems!</h3>
                <a href="{% url 'myapp:leaderboard' %}">Please visit our leaderboard!</a>
            {% else %}
                <form action="" enctype="multipart/form-data" method="post" role="form">
                    {% csrf_token %}
                    {% include 'myapp/form-template.html' %}
                    <div class="wrapper">
                        <button type="submit" id="myBtn" class="button btn">Submit</button>
                    </div>
                    <!-- The Modal -->
                    <div id="myModal" class="modal">

                        {% if msg != 'x' %}
                          <!-- Modal content -->
                          <div class="modal-content">
                            <span class="close">&times;</span>
                            <p>{{ msg }}</p>
                          </div>
                        {% endif %}

                    </div>
                </form>
            {% endif %}
        </div>
    </div>
    <script>
        // Get the modal
        var modal = document.getElementById('myModal');

        // Get the button that opens the modal
        var btn = document.getElementById("myBtn");
        var str = "{{ msg }}"
        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];

        // When the user clicks the button, open the modal
        if(str=='Incorrect answer, please try again!')
        {
            modal.style.display = "block";
        }

        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
            modal.style.display = "none";
        }

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>
{% endblock %}

myapp/templates/myapp/leaderboard.html
{% extends 'myapp/base.html' %}

{% block body %}
<div class="container" style="opacity: 0.9;>
    <div class="panel panel-default" style="border: 0; border-radius: 3px;">
        <div class="panel-body" style="border: 0; padding: 0;">
            <table class="responsive" style="background: url('http://www.innatthecrossroads.com/wp-content/uploads/2016/10/Wooden-background-texture-pattern-images-for-website-HD-template-PSD-free-download.jpg'); background-repeat: no-repeat; background-attachment: fixed; background-size: cover; color: #ffe3b4; padding: 40px 0;">
                <thead>
                  <tr>
                      <th>Rank</th>
                      <th>Name</th>
                      <th>Score</th>
                  </tr>
                </thead>
                <tbody>
                    {% for profile in profiles %}
                    {% if not profile.user.is_superuser %}
                    <tr>
                    <td></td>
                       {% if request.user == profile.user %}
                        <td style="background-color: #000;color:#fff; padding: 12px 0">
                            {{ profile.user.first_name }} {{ profile.user.last_name }}
                        </td>
                        {% else %}
                        <td style="padding: 12px 0">
                            {{ profile.user.first_name }} {{ profile.user.last_name }}
                        </td>
                        {% endif %}
                        <td style="padding: 12px 0">
                            {{ profile.solved|add:"-1" }}
                        </td>
                    </tr>
                    {% else %}
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    var addSerialNumber = function () {
    var i = 0
    $('table tr').each(function(index) {
        $(this).find('td:nth-child(1)').html(index-1+1);
    });
};

addSerialNumber();
</script>
{% endblock %}

myapp/templates/myapp/logs_data.html
{% extends 'myapp/base.html' %}

<!DOCTYPE html>
<html>
<head>
	<title>Xunbao | Logs</title>
	<style type="text/css">
	{%block style%}
		th{
			padding: 10px;
			border: 2px solid black;
		}
		td{
			padding: 10px;
			border: 2px solid black;
		}
		
		{%endblock%}
	</style>
</head>
<body>
	{% block body %}
<table style="font-size: 20px;text-align: center;padding:10px;border-color: 5px solid black;background-color: #fff;opacity: 0.7;">
	<tr>
	<th>Username</th>
	<th>User fid</th>
	<th>Answer</th>
	<th>Status</th>
	<th>time</th>
</tr>
{%for i in logs%}
<tr>
	<td>{{i.user.first_name}} {{i.user.last_name}}</td>
	<td>{{i.user.username}}</td>
	<td>{{i.answer}}</td>
	<td>{{i.status}}</td>
	<td>{{i.time}}</td>
</tr>
{%endfor%}
</table>
{% endblock %}
</body>
</html>

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{%load static%}

{% block body %}
    <div class="container-fluid">
      <div class="row no-gutters">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <div class="alert alert-info alert-dismissible show" role="alert">
            To all Lara Crofts and Indiana Jones out there, this time we are sending you back in time where great many incidents occurred. You have to find yourselves the hidden treasure down your path. It is up to you how you find the treasure, hidden in the depths of the Internet, do not lose trail while following or you might get lost forever. Are you ready for the adventure? 
Xunbao is a multi-level contest where you will be given cues to solve.<br><br>
With every step challenging your wit, it is a race against time and fellows. So get on your Black Pearls, in other words your Mobile and surf the waves on the internet to claim your fame.<br><br>
This year the stakes could not get any higher. Conquerors of the event will get prizes like Mi Band 2 and more exciting goodies from <b><a href="http://ocul.in">ocul.in</a></b>, a simple URL Shortening Service.
<br><br><br>
<b>GOOD LUCK EXPLORING!</b>
            <!--<button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>-->
            </button>
          </div>
        </div>
        <div class="col-md-3"></div>
      </div>
      <div class="row no-gutters">
        <div class="col-md-3"></div>
        <div class="col-md-6" align="middle">
          <a href="{% url 'social:begin' 'facebook' %}"><button class="loginBtn loginBtn--facebook">
            Login with Facebook
              </button></a>
        </div>
        <div class="col-md-3"></div>
      </div>
    </div>
{% endblock %}